services:
  backend:
    build: ./backend
    container_name: jobder_backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
      - chroma_data:/app/chroma_db
    networks:
      - jobder_network

  redis:
    image: redis:7-alpine
    container_name: jobder_redis
    restart: unless-stopped
    networks:
      - jobder_network

  postgres:
    image: postgres:15
    container_name: jobder_postgres
    restart: always
    environment:
      POSTGRES_USER: jobder
      POSTGRES_PASSWORD: jobder-bdD
      POSTGRES_DB: jobder_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/02_seed.sql
    networks:
      - jobder_network

  frontend:
    build: ./frontend
    container_name: jobder_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - jobder_network

networks:
  jobder_network:
    driver: bridge

volumes:
  postgres_data:
  chroma_data:
